### PR TITLE
add hui/html

### PR DESCRIPTION
**Pull request by mafintosh**
We use this as a shorthand in our HUI component, https://github.com/hyperdivision/hui

### CODE REVIEW

**Comment by emilbayes** [comment]
@goto-bus-stop @bcomnes Can we merge this? :)

**Comment by goto-bus-stop** [comment]
this list is duplicated in lib/babel.js (`nanohtmlModuleNames` variable), could it be updated there as well? the babel plugin has an option to specify custom module names, but the default should be the same ideally.

**Comment by mafintosh** [comment]
@goto-bus-stop fixed

**Comment by goto-bus-stop** [comment]
:package: 1.6.0

**Pull request merged**
