### PR TITLE
Allow multiple elements in root with Fragments

### PR DESCRIPTION
**Pull request by finnp**
This will allow
```js
html`
  <div>Hallo</div>
  <div>Welt</div>
`
```

This will return a [DocumentFragment](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment) with the children `<div>Hello</div>` and `<div>Welt</div>`

Also see https://github.com/choojs/hyperx/issues/65
Depends on https://github.com/choojs/hyperx/pull/66

- [x] browser
- [x] babel
- [x] server
- [x] transform

### CODE REVIEW

**Comment by bcomnes** [comment]
Does this work?

```js
html`
<div>
${() => {
  return html`
    <div>Hallo</div>
    <div>Welt</div>
  `
  }()}
</div>
`
```

Or do you have to move the contents of the fragment out of the fragment?

**Comment by finnp** [comment]
@bcomnes Yes this should work. When doing `div.appendChild(fragment)` the fragment will be discarded. So the div will have the two children `<div>Hallo</div>` and `<div>Welt</div>`

**Comment by AndyOGo** [comment]
I really like this 👍

**Comment by finnp** [comment]
@goto-bus-stop I've seen that you merged the `createFragment` PR on hyperx. I've updated this PR to the latest master. Do you want to merge this in? I could also add something for the documentation.

**Comment by finnp** [comment]
@goto-bus-stop I added a section for this. Tried to add a nice explanation, but couldn't come up with any. I think it works this way though. What do you think?

**Pull request merged**
