### PR TITLE
Pass filename to ast-transform for sourcemaps

### PR DESCRIPTION
**Pull request by mantoni**
This is a solution for #139. Once I had it reproduced properly, it was relatively clear what was going 😄

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
great, thanks :) did you try this patch in devtools? I don't remember if you need to pass the full file name or just the basename without the directory. if you tried it like this and it worked then LGTM

**Comment by mantoni** [comment]
Yeah, it works in dev tools, but I need to remove the basedir, I think. Looking into it.

**Comment by mantoni** [comment]
I added a commit to make the filename relative. I hope it was the right thing to check for the `basedir` option and fall back to `process.cwd()`. That's how browserify seems to handle it.

**Comment by mantoni** [comment]
Anything else I can do to get this landed? This change works fine for me.

**Pull request merged**
