### PR TITLE
Preserve trailing newline whitespace before text nodes

### PR DESCRIPTION
**Pull request by JacobEvelyn**
#142 was a great start but it didn't quite fix the whitespace issue for me around text nodes. See the test in this PR for an example of a problem I'm running into.

### CODE REVIEW

**Comment by JacobEvelyn** [comment]
Any movement on this @bcomnes ?

**Comment by bcomnes** [comment]
Not yet. Been moving all week (ca to Utah). I might have some time this week though once I get the truck unloaded. 

Otherwise someone else should beat me to it.

**Comment by JacobEvelyn** [comment]
No worries! Good luck with the move! 🚚

**Comment by JacobEvelyn** [comment]
This PR is now three months old. @bcomnes any reason not to merge it?

Hope Utah's treating you well!

**Comment by perguth** [comment]
I think that's in line with what HTML does/a webdev expects.

**Comment by perguth** [comment]
Funny, I now have a similar problem: I would to render a newline character without using `<br>` because I am outputting into a `<code>` block. Having the newlines preserved would be nice ✨

**Comment by bcomnes** [comment]
Sorry for the delay, this should be going out shortly.

**Pull request merged**
