### PR TITLE
Allow createElement to be required without hyperx

### PR DESCRIPTION
**Pull request by ajoslin**
Closes #20. This is the same thing as #20, opened against the latest
code.

### CODE REVIEW

**Comment by AndyOGo** [comment]
@ajoslin 
This PR has conflicts. Is it still the intention to get this merged?

**Comment by ajoslin** [comment]
This is over a year old, so I'm sure merging it is more trouble than it's worth. If the maintainers want this to happen, we should get a word from them first before opening another PR.

**Comment by bcomnes** [comment]
So this just pulls out createElement into its own function? I think thats fine if people are still interested.

**Comment by bcomnes** [comment]
If not lets close.

**Comment by bcomnes** [comment]
Yeah ok looked more, this would be easier to open a new PR.

**Pull request closed without merging**
